export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CREATE_MANAGER_REQUEST = 'CREATE_MANAGER_REQUEST';
export const CREATE_MANAGER_SUCCESS = 'CREATE_MANAGER_SUCCESS';
export const CREATE_MANAGER_FAIL = 'CREATE_MANAGER_FAIL';
export const SET_MANAGER = 'SET_MANAGER';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';